from database.entities.armors import Armors
from database.entities.classes import Classes
from database.entities.monsters import Monsters
from database.entities.monsters_chances import MonstersChances
from database.entities.monsters_weapons import MonstersWeapons
from database.entities.level_ups import LevelUps
from database.entities.preficiencies_weapons import PreficienciesWeapons
from database.entities.weapon_damage_type import WeaponDamageType
from database.entities.weapons import Weapons
